---

- name: restart mattermost
  service:
    name: mattermost.service
    state: restarted

- name: restart nginx
  service:
    name: nginx.service
    state: restarted

- name: reload nginx
  service:
    name: nginx.service
    state: reloaded
